### ISSUE TITLE
Wallpaper: Background wall turns black when the source image is deleted

### ISSUE THREAD

**Issue by Rezonansowy** [linuxmint/cinnamon-control-center#102] opened 2015-01-28 13:33 UTC
Background image should be copied somewhere to prevent black screen.

**Comment by Vahan86** [comment] 2016-11-01 19:42
Can't reproduce this in Cinnamon 3.0.7. Desktop background stays the same when the source image is deleted.

@Rezonansowy, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment] 2016-12-01 07:03
@JosephMcc, can we close the issue?

**Closed** 2016-12-01 07:27 UTC

**Comment by leigh123linux** [comment] 2016-12-01 07:39
cinnamon-control-center doesn't control the background settings, the code for that is in cinnamon.

@Rezonansowy 
cinnamon-settings background has the ability to add new folders to watch, I suggest in future you add a ~/.backgrounds directory and use it.

**Comment by Rezonansowy** [comment] 2016-12-01 11:48
@leigh123linux OK, thanks for your hint.
